import type { BrandSpec, CampaignPageSpec, DeploymentManifest } from "./types";

export function createDefaultBrandSpec(name = "Migrated Brand"): BrandSpec {
  return {
    id: "brand-default",
    name,
    colors: {
      canvas: "#ffffff",
      surface: "#ffffff",
      surfaceAlt: "#f8fafc",
      text: "#0f172a",
      textMuted: "#475569",
      border: "#e2e8f0",
      brand: "#2563eb",
      brandContrast: "#ffffff",
      accent: "#2563eb",
      accentContrast: "#ffffff",
    },
    typography: {
      display: "Inter",
      heading: "Inter",
      body: "Inter",
      label: "Inter",
    },
    spacingDensity: "comfortable",
    radius: "lg",
    voice: {
      formality: "neutral",
      energy: "confident",
      clarity: "plainspoken",
      personality: "friendly",
    },
  };
}

export function createEmptyCampaignPageSpec(title = "Untitled campaign page"): CampaignPageSpec {
  return {
    id: "page-default",
    title,
    slug: "/",
    goal: "lead",
    brand: createDefaultBrandSpec(),
    contentStrategy: {
      goal: "lead",
    },
    seo: {
      title,
      description: "Migrated campaign page generated by Stitch.",
    },
    sections: [],
  };
}

export function createDefaultDeploymentManifest(): DeploymentManifest {
  return {
    type: "static-campaign-site",
    buildCommand: "npm run build",
    outputDir: "dist",
    routes: [{ path: "/", file: "index.html" }],
    redirects: [],
    headers: [
      {
        path: "/*",
        headers: {
          "cache-control": "public, max-age=3600",
        },
      },
    ],
  };
}
