export const DESIGN_CONTRACT_VERSION = "0.1.0" as const;

export const canonicalDesignContract = {
  kind: "StitchDesignContract",
  version: DESIGN_CONTRACT_VERSION,
  purpose:
    "Normalize migrated marketing pages into a semantic, brand-aware, campaign-oriented page model that can be safely edited, regenerated, reviewed, and deployed.",
  hierarchy: ["brand", "page", "section", "block", "element", "token"],
  principles: [
    "Semantic before visual",
    "Spec before code",
    "Small vocabulary, infinite composition",
    "Every editable object declares safe operations",
    "Client feedback is untrusted until owner-approved",
    "Model output is untrusted until validated",
  ],
  brandTokenRoles: {
    color: [
      "canvas",
      "surface",
      "surfaceAlt",
      "surfaceElevated",
      "surfaceInverse",
      "text",
      "textMuted",
      "textSubtle",
      "textInverse",
      "border",
      "borderStrong",
      "brand",
      "brandContrast",
      "accent",
      "accentContrast",
      "success",
      "warning",
      "danger",
    ],
    typography: ["display", "heading", "body", "label", "mono"],
    spacing: ["pagePadding", "sectionPadding", "sectionGap", "blockGap", "itemGap", "inlineGap"],
    radius: ["button", "card", "media", "input"],
  },
  contentStrategy: {
    goals: ["lead", "signup", "bookCall", "purchase", "download", "waitlist", "awareness", "eventRegistration"],
    primitives: [
      "audience",
      "pain",
      "promise",
      "outcome",
      "mechanism",
      "differentiator",
      "proof",
      "objection",
      "riskReversal",
      "urgency",
      "cta",
      "trust",
      "offer",
    ],
    persuasionFlow: ["attention", "relevance", "desire", "trust", "action"],
  },
  sections: [
    "Hero",
    "LogoCloud",
    "Problem",
    "Benefits",
    "FeatureGrid",
    "HowItWorks",
    "Testimonials",
    "Stats",
    "Offer",
    "Pricing",
    "FAQ",
    "FinalCTA",
    "Footer",
  ],
  elements: ["Heading", "Text", "Button", "Link", "Image", "Badge", "Card", "List", "Form", "Icon"],
  editPolicy: {
    lowRisk: ["copyChange", "ctaLabelChange", "visualVariantChange", "spacingDensityChange", "sectionToneChange"],
    mediumRisk: ["reorderSection", "addSection", "removeSection", "replaceImage", "editHref"],
    highRisk: ["changeFormDestination", "changeAnalytics", "changePricing", "changeLegalText", "injectScript"],
    blocked: ["javascriptHref", "hiddenDataCapture", "secretExposure", "unapprovedTracking", "unauthorizedPublish"],
  },
} as const;
